'use strict';
const S=PortfolioSchedule, baseline=JSON.parse(document.getElementById('plan-data').textContent), key='dp-portfolio-scenario-v1:'+baseline.revision;
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let plan=structuredClone(baseline), view='timeline', selected='', results={}, saveMessage='';
try{const stored=localStorage.getItem(key);if(stored){const parsed=JSON.parse(stored);S.validate(parsed);plan=parsed;saveMessage='Restored local scenario';}}catch(e){saveMessage='Local save unavailable; use Export scenario.';}
function persist(){try{localStorage.setItem(key,JSON.stringify(plan));saveMessage='Scenario saved in this browser';}catch(e){saveMessage='Local save unavailable; use Export scenario.';}$('save-status').textContent=saveMessage;}
function tasks(){return plan.tasks.filter(t=>!$('project').value||t.project===$('project').value);}
function projectName(id){return plan.projects.find(p=>p.id===id)?.name||id;}
function num(n){return n===null?'?':Number(n.toFixed(2));}
function link(url,label){try{const u=new URL(url);return ['https:','http:'].includes(u.protocol)?`<a href="${esc(u.href)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`:esc(label);}catch(e){return esc(label);}}
function controls(){const prev=$('project').value;$('project').innerHTML='<option value="">All projects</option>'+plan.projects.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');$('project').value=plan.projects.some(p=>p.id===prev)?prev:(plan.projects.some(p=>p.id==='bagworm')?'bagworm':'');if(plan.scenario_start)$('start').value=plan.scenario_start;$('resources').checked=plan.scenario_resources!==false;}
function currentFinish(mode){const tt=tasks();if(!tt.length||tt.some(t=>results[mode].rows[t.id].finish===null))return null;return Math.max(...tt.map(t=>results[mode].rows[t.id].finish));}
function ready(t){return t.status!=='done'&&!t.blocker&&t.deps.every(id=>plan.tasks.find(t=>t.id===id)?.status==='done');}
function draw(){
 try{for(const m of ['minimum','likely','downside'])results[m]=S.schedule(plan,m,$('resources').checked);$('error').textContent='';}catch(e){$('error').textContent=e.message;$('view').innerHTML='';$('details').innerHTML='';return;}
 const tt=tasks(), f=currentFinish('likely'), mi=currentFinish('minimum'), down=currentFinish('downside');
 $('metrics').innerHTML=[['Minimum scenario',mi===null?'Needs estimates':num(mi)+' workdays'],['Likely scenario',f===null?'Needs estimates':num(f)+' workdays'],['Downside scenario',down===null?'Needs estimates':num(down)+' workdays'],['Ready by evidence',tt.filter(ready).length+' packets']].map(([l,v])=>`<div class="metric"><small>${l}</small><strong>${v}</strong></div>`).join('');
 $('footer').innerHTML=`Source snapshot: ${esc(plan.as_of||'none')} · ${esc(plan.revision)}. Durations are remaining working-day spans, not timesheet hours. Weekends skipped; holidays and individual work calendars are not modeled. Resource mode reserves one exclusive slot per named resource, using packet priority and allowing idle gaps. Conditional bars assume open gates resolve. Downside is a stress scenario, not P80 or a promise. ${link('https://www.gao.gov/products/gao-16-89g','Scheduling reference: GAO')}`;
 $('save-status').textContent=saveMessage||'Baseline snapshot · edits stay local';
 document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
 if(view==='timeline')timeline(tt);if(view==='network')network(tt);if(view==='ready')readyView(tt);if(view==='portfolio')portfolio();
 if(!selected||!plan.tasks.some(t=>t.id===selected)||!tt.some(t=>t.id===selected))selected=tt[0]?.id||'';
 detail();
}
function timeline(tt){
 const horizon=Math.max(1,...plan.tasks.map(t=>results.downside.rows[t.id].finish||0));
 $('view').innerHTML='<h2>How the work unfolds</h2><div class="legend"><span><i class="dot" style="background:#93b9a3"></i>Minimum</span><span><i class="dot" style="background:#166348"></i>Likely</span><span><i class="dot" style="background:#d6aa80"></i>Downside</span><span>Striped = conditional · Orange outline = portfolio finish driver</span></div><p class="muted">Each row shows three recalculated scenarios. Hidden-project dependencies still apply. Packets with unknown durations cannot reserve resources: these partial forecasts may understate contention.</p><div class="gantt"><div class="grow"><small>Work packet / proposed resource</small><div class="axis">'+[0,.2,.4,.6,.8,1].map(f=>`<span>Day ${num(f*horizon)}</span>`).join('')+'</div></div>'+tt.map(t=>{const r=results.likely.rows[t.id];return `<div class="grow"><button class="glabel" data-task="${esc(t.id)}"><strong>${esc(t.title)}</strong><br><small>${esc(t.resources.join(' + ')||'Resource TBD')} · ${esc(t.status)}${r.resourceDelay?' · '+num(r.resourceDelay)+'d resource wait':''}</small></button><div class="track">${r.finish===null?'<small>Needs an estimate or estimated predecessor</small>':['minimum','likely','downside'].map(m=>{const rr=results[m].rows[t.id];return rr.finish===null?'':`<div class="bar ${m} ${rr.conditional?'conditional':''} ${m==='likely'&&results.likely.driving.includes(t.id)?'driver':''}" style="left:${rr.start/horizon*100}%;width:${Math.max(.25,rr.duration/horizon*100)}%" title="${m}: day ${num(rr.start)}–${num(rr.finish)}"></div>`;}).join('')}</div></div>`;}).join('')+'</div>'+(tt.length?'':'<div class="empty">Import a portfolio scenario to begin.</div>');
}
function network(tt){
 const ids=new Set(tt.map(t=>t.id)), positions=Object.create(null), counts=Object.create(null);let maxDepth=0;
 for(const t of tt){const d=results.likely.rows[t.id].depth;positions[t.id]={x:20+d*270,y:30+(counts[d]||0)*118};counts[d]=(counts[d]||0)+1;maxDepth=Math.max(maxDepth,d);}
 const width=Math.max(650,(maxDepth+1)*270),height=Math.max(240,...Object.values(counts).map(n=>n*118+45));
 let edges='';for(const t of tt)for(const id of t.deps)if(ids.has(id)){const a=positions[id],b=positions[t.id];edges+=`<path d="M${a.x+235},${a.y+39} C${a.x+253},${a.y+39} ${b.x-18},${b.y+39} ${b.x},${b.y+39}" fill="none" stroke="#91a69c" stroke-width="2" marker-end="url(#arrow)"/>`;}
 const nodes=tt.map(t=>{const p=positions[t.id],r=results.likely.rows[t.id];const words=t.title.split(' '),lines=[''];for(const w of words){let last=lines.length-1;if((lines[last]+' '+w).length>28)lines.push(w);else lines[last]+=(lines[last]?' ':'')+w;}return `<g class="node" data-task="${esc(t.id)}" role="button" tabindex="0" aria-label="${esc(t.title)}"><rect x="${p.x}" y="${p.y}" width="235" height="92" rx="9" fill="${t.id===selected?'#e7eee4':'#fff'}" stroke="${t.blocker?'#be6434':'#93b4a2'}"/><text x="${p.x+12}" y="${p.y+21}" fill="#17332e" font-size="12">${lines.slice(0,2).map((l,i)=>`<tspan x="${p.x+12}" dy="${i?16:0}">${esc(l)}</tspan>`).join('')}</text><text x="${p.x+12}" y="${p.y+64}" fill="#60756e" font-size="10">${esc(t.resources.join(' + ')||'Resource TBD')} · ${num(t.likely)}d</text><text x="${p.x+12}" y="${p.y+80}" fill="#a3572e" font-size="10">${esc(t.blocker?'Open gate':r.finish===null?'Needs estimate':r.conditional?'Conditional':'Estimated')}${t.deps.some(id=>!ids.has(id))?' · external predecessor':''}</text></g>`;}).join('');
 $('view').innerHTML='<h2>What unlocks what</h2><p class="muted">Left → right shows technical precedence. Nodes on separate branches may run in parallel if resources permit. Select a node for its blockers and evidence.</p><div class="network"><svg aria-label="Task dependency graph" role="group" width="'+width+'" height="'+height+'"><defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L10,5 L0,10" fill="#91a69c"/></marker></defs>'+edges+nodes+'</svg></div>';
}
function card(t){const r=results.likely.rows[t.id];return `<article class="card"><span class="tag">${esc(projectName(t.project))}</span><span class="tag">${esc(t.approval||'proposed')}</span><h3>${esc(t.title)}</h3><p>${esc(t.blocker||t.done_when||'Define completion evidence.')}</p><small>${esc(t.resources.join(' + ')||'Owner TBD')} · ${num(t.minimum)} / ${num(t.likely)} / ${num(t.downside)} workdays${r.conditional?' · conditional':''}</small><br><button data-task="${esc(t.id)}">Review packet</button></article>`;}
function readyView(tt){const rr=tt.filter(ready),bb=tt.filter(t=>t.status!=='done'&&!ready(t));$('view').innerHTML='<h2>Keep the next result ready</h2><p class="muted">Evidence-ready means predecessors are marked done and no open blocker is recorded. Approval and actual availability still apply.</p><h3>Ready by evidence</h3><div class="cards">'+(rr.map(card).join('')||'<p class="muted">No ready packets yet.</p>')+'</div><h3 style="margin-top:20px">Waiting on evidence, decisions or work</h3><div class="cards">'+bb.map(card).join('')+'</div>';}
function portfolio(){ $('view').innerHTML='<h2>The whole portfolio</h2><p class="muted">Near-term checkpoints are distinct from the contract finish line. Unknown forecasts remain unknown.</p><div class="cards">'+plan.projects.map(p=>{const end=results.likely.projectFinishes[p.id];return `<article class="card"><span class="tag">${esc(p.category||'Project')}</span><h3>${esc(p.name)}</h3><p>${esc(p.milestone||'Milestone to define')}</p><p><strong>${end===null?'Needs estimates':S.workDate($('start').value,end)+' · conditional forecast'}</strong></p><small>${esc(p.note||'')}</small><p>${link(p.source,'Source context')}</p><button data-project="${esc(p.id)}">Open project</button></article>`;}).join('')+'</div>';}
function detail(){const t=plan.tasks.find(t=>t.id===selected);if(!t){$('details').innerHTML='<h3>Choose a work packet</h3><p class="muted">Dependencies, estimates and evidence appear here.</p>';return;}const r=results.likely.rows[t.id];$('details').innerHTML=`<small>${esc(projectName(t.project))}</small><h2>${esc(t.title)}</h2><span class="tag">${esc(t.approval||'proposed')} · scenario</span><p>${link(t.source,'Open supporting context')}</p><div class="hint">${esc(t.estimate_basis||'Draft planning estimate; owner validation needed.')}</div><form id="edit"><label>Packet title<input name="title" value="${esc(t.title)}" required></label><div class="estimates">${['minimum','likely','downside'].map(m=>`<label>${m}<input name="${m}" aria-label="${m} workdays" type="number" min="0" max="1000" step="0.25" value="${t[m]??''}" placeholder="?"/></label>`).join('')}</div><small>Remaining workdays; blank means unknown.</small><label>Predecessor IDs (comma separated)<input name="deps" value="${esc(t.deps.join(', '))}"></label><small>This packet: ${esc(t.id)}</small><label>People / equipment (exclusive slots)<input name="resources" value="${esc(t.resources.join(', '))}"></label><label>Earliest start, workday offset<input name="release" type="number" min="0" step="0.25" value="${t.release}"></label><label>Status<select name="status">${['proposed','in_progress','done'].map(s=>`<option ${t.status===s?'selected':''}>${s}</option>`).join('')}</select></label><label>Open blocker<textarea name="blocker">${esc(t.blocker||'')}</textarea></label><label>Completion evidence<textarea name="done_when">${esc(t.done_when||'')}</textarea></label><label class="check"><input name="availability_confirmed" type="checkbox" ${t.availability_confirmed?'checked':''}>Availability confirmed in this scenario</label><button type="submit">Apply to scenario</button></form><p class="muted">${r.finish===null?'No forecast until estimates are complete.':`Likely finish: ${esc(S.workDate($('start').value,r.finish))}. ${num(r.resourceDelay)} workdays added by resource contention.`}</p><h3>Unblocks</h3><p>${esc(plan.tasks.filter(x=>x.deps.includes(t.id)).map(x=>x.title).join('; ')||'No successor recorded')}</p><button id="add">Add following packet</button>`;
 $('edit').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),copy=structuredClone(plan),n=copy.tasks.find(x=>x.id===t.id);for(const k of ['title','status','blocker','done_when'])n[k]=f.get(k).trim();for(const k of ['minimum','likely','downside'])n[k]=f.get(k)===''?null:Number(f.get(k));n.release=Number(f.get('release'));for(const k of ['deps','resources'])n[k]=[...new Set(f.get(k).split(',').map(x=>x.trim()).filter(Boolean))];n.availability_confirmed=f.has('availability_confirmed');try{S.validate(copy);plan=copy;persist();draw();}catch(e){$('error').textContent=e.message;}};
 $('add').onclick=()=>{const id='packet-'+crypto.randomUUID().slice(0,8);plan.tasks.push({id,project:t.project,title:'New work packet',deps:[t.id],resources:[],minimum:null,likely:null,downside:null,release:0,status:'proposed',approval:'proposed',blocker:'Define result and owner',availability_confirmed:false,source:t.source});selected=id;persist();draw();};
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-view],[data-task],[data-project]');if(!b)return;if(b.dataset.view)view=b.dataset.view;if(b.dataset.task)selected=b.dataset.task;if(b.dataset.project){$('project').value=b.dataset.project;view='timeline';}draw();});
document.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)&&e.target.matches('.node')){e.preventDefault();selected=e.target.dataset.task;draw();}});
$('project').onchange=draw;$('resources').onchange=()=>{plan.scenario_resources=$('resources').checked;persist();draw();};$('start').onchange=()=>{plan.scenario_start=$('start').value;persist();draw();};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(plan,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='cislune-planning-scenario.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000);};
$('import').onclick=()=>$('file').click();$('file').onchange=async()=>{try{const f=$('file').files[0];if(!f)return;if(f.size>2000000)throw Error('Use a file smaller than 2 MB.');const p=JSON.parse(await f.text());S.validate(p);plan=p;controls();persist();draw();}catch(e){$('error').textContent=e.message;}$('file').value='';};
$('reset').onclick=()=>{if(!confirm('Reset browser scenario edits to the loaded source snapshot? Export first to keep a copy.'))return;plan=structuredClone(baseline);controls();persist();draw();};
controls();draw();
